CREATE DATABASE ChatDB;
GO
USE ChatDB;
GO
CREATE TABLE Users (id INT IDENTITY PRIMARY KEY, username NVARCHAR(50) UNIQUE, password_hash NVARCHAR(255));
CREATE TABLE Messages (id INT IDENTITY, from_user NVARCHAR(50), to_room NVARCHAR(50), content NVARCHAR(500), timestamp DATETIME DEFAULT GETDATE());